### ISSUE TITLE
Logo, Level 14:  Third column of table easily becomes invisible.

### ISSUE THREAD

**Issue by TentativeConvert** [hhu-adam/Robo#22]
On not-super-large screens, the table supplied in the hints is too wide and parts of it easily become hidden.  Can we somehow make this table more narrow?

**Comment by joneugster** [comment]
Fixed in `lean4game` by adding the following CSS:

```
 .chat .message {
   margin-left: .5em;
   margin-right: .5em;
+  overflow-x: auto;
 }
```
