### ISSUE TITLE
Predicate/Quantus, Level 10:  add additional warning about branch not yet covered

### ISSUE THREAD

**Issue by TentativeConvert** [hhu-adam/Robo#24]
Players that start with `unfold Odd`, `push_neg` get a warning “Dieser Lösungsweg scheint mir zu schwierig …”.
Players that start with `push_neg`, `unfold Odd` do not get that warning.  I suppose that this latter approach is equally difficult. (I haven’t check this in detail, but I was only able to finish from here using the `have` tactic, which is not unlocked at this point.)

**Comment by joneugster** [comment]
added the hint again after

```
push_neg
unfold Odd
intro n
```

that way it catches a `unfold` after `intro` too.
