### ISSUE TITLE
Implis 13:  add `imp_iff_not_or` to Inventory

### ISSUE THREAD

**Issue by TentativeConvert** [hhu-adam/Robo#28]
The level conists of a proof of <https://leanprover-community.github.io/mathlib4_docs/Init/PropLemmas.html#Decidable.imp_iff_not_or>.  This would be a natural lemma to use in the proof of the Drinker's paradox in the final level of Predicate/Quantus.

**Comment by joneugster** [comment]
It's in the inventory, just under the `[anonymous]` tab because it's in no namespace and no documentation has been written.

**Comment by joneugster** [comment]
now I moved it to the "Logic" tab.
