### ISSUE TITLE
Babylon Level 4 Latex-summary mismatch

### ISSUE THREAD

**Issue by bernborgess** [hhu-adam/Robo#32]
# In the 4th level of Babylon:
![4_6_summe](https://github.com/hhu-adam/Robo/assets/62393097/36b450d4-c9b7-42ab-b825-d64cb4cef9cd)
The formula states
$$\sum_{i=0}^{n}{(2n+1)} = n^2$$
Which is false for many examples. The statement in lean induces it to actually be
$$\sum_{i=0}^{n-1}{(2i+1)} = n ^2$$
I would change it myself and open a PR, but I couldn't find where it is defined in the repo.

**Comment by TentativeConvert** [comment]
Thank your for the report!  I actually spotted the same typo a few days ago and corrected it in the repository:

<https://github.com/hhu-adam/Robo/blob/fc1de96df4abc22c54b6b5c027f1886cda230972/Game/Levels/Sum/L04_SumOdd.lean#L20>

I guess the fix will go live within the next week.
